export type EntryStatus = "verified" | "session-only" | "invalid" | "connected" | "built-in";
export type Surface = "cli" | "agent-tool" | "slash";

export interface Entry {
  id: string;
  surface: Surface;
  name: string;
  category: string;
  description: string;
  example?: string;
  actions?: string[];
  whenToUse?: string;
  status: EntryStatus;
}

export const CLI_CATEGORIES = ["Gateway", "Tasks", "Skills", "System", "Misc", "Invalid"] as const;
export const TOOL_CATEGORIES = [
  "Files",
  "Execution",
  "Sessions",
  "Channels",
  "Media",
  "Web",
  "Nodes",
  "Memory",
  "Browser",
  "Other",
] as const;

export const ENTRIES: Entry[] = [
  // ============ CLI ============
  {
    id: "cli-gateway-run",
    surface: "cli",
    name: "openclaw gateway run",
    category: "Gateway",
    description: "Run the WebSocket gateway in the foreground.",
    example: "openclaw gateway run",
    status: "verified",
  },
  {
    id: "cli-gateway-status",
    surface: "cli",
    name: "openclaw gateway status",
    category: "Gateway",
    description: "Show service status plus connectivity and capability.",
    example: "openclaw gateway status --require-rpc --json",
    status: "verified",
  },
  {
    id: "cli-gateway-probe",
    surface: "cli",
    name: "openclaw gateway probe",
    category: "Gateway",
    description: "Probe the gateway and return a structured diagnostic.",
    example: "openclaw gateway probe --json",
    status: "verified",
  },
  {
    id: "cli-gateway-discover",
    surface: "cli",
    name: "openclaw gateway discover",
    category: "Gateway",
    description: "Find local and wide-area gateway beacons.",
    example: "openclaw gateway discover",
    status: "verified",
  },
  {
    id: "cli-gateway-stability",
    surface: "cli",
    name: "openclaw gateway stability",
    category: "Gateway",
    description: "Show recent stability diagnostics.",
    example: "openclaw gateway stability",
    status: "verified",
  },
  {
    id: "cli-gateway-call-health",
    surface: "cli",
    name: "openclaw gateway call health",
    category: "Gateway",
    description: "Direct RPC: liveness check + loaded plugins.",
    example: "openclaw gateway call health",
    status: "verified",
  },
  {
    id: "cli-gateway-call-status",
    surface: "cli",
    name: "openclaw gateway call status",
    category: "Gateway",
    description: "Direct RPC: runtime version, channels, tasks, sessions.",
    example: "openclaw gateway call status",
    status: "verified",
  },
  {
    id: "cli-gateway-call-config",
    surface: "cli",
    name: "openclaw gateway call config.get",
    category: "Gateway",
    description: "Direct RPC: read effective gateway configuration.",
    example: "openclaw gateway call config.get",
    status: "verified",
  },
  {
    id: "cli-gateway-call-logs",
    surface: "cli",
    name: "openclaw gateway call logs.tail",
    category: "Gateway",
    description: "Direct RPC: tail recent gateway log lines.",
    example: "openclaw gateway call logs.tail",
    status: "verified",
  },
  {
    id: "cli-tasks",
    surface: "cli",
    name: "openclaw tasks",
    category: "Tasks",
    description: "Inspect durable background task state.",
    example: "openclaw tasks",
    status: "verified",
  },
  {
    id: "cli-skills",
    surface: "cli",
    name: "openclaw skills",
    category: "Skills",
    description: "List and inspect available skills.",
    example: "openclaw skills",
    status: "verified",
  },
  {
    id: "cli-system",
    surface: "cli",
    name: "openclaw system",
    category: "System",
    description: "System events, heartbeat, and presence.",
    example: "openclaw system",
    status: "verified",
  },
  {
    id: "cli-terminal",
    surface: "cli",
    name: "openclaw terminal",
    category: "Misc",
    description: "Open a local terminal UI (alias for tui --local).",
    example: "openclaw terminal",
    status: "verified",
  },
  {
    id: "cli-docs",
    surface: "cli",
    name: "openclaw docs",
    category: "Misc",
    description: "Search local docs index. Limited coverage in current build.",
    example: 'openclaw docs "gateway"',
    status: "verified",
  },
  {
    id: "cli-flag-container",
    surface: "cli",
    name: "--container <name>",
    category: "Misc",
    description: "Run the CLI inside a running Podman/Docker container.",
    example: "openclaw --container openclaw gateway status",
    status: "verified",
  },
  {
    id: "cli-flag-dev",
    surface: "cli",
    name: "--dev",
    category: "Misc",
    description: "Dev profile: isolate state under ~/.openclaw-dev.",
    example: "openclaw --dev gateway run",
    status: "verified",
  },
  {
    id: "cli-bad-tools-list",
    surface: "cli",
    name: "openclaw tools list",
    category: "Invalid",
    description: "Not a real command — CLI suggests 'hooks'. Tool discovery happens via the chat /tools slash command.",
    status: "invalid",
  },
  {
    id: "cli-bad-call-help",
    surface: "cli",
    name: "openclaw gateway call help",
    category: "Invalid",
    description: "Unknown RPC method. Use 'gateway call status' or 'health' instead.",
    status: "invalid",
  },
  {
    id: "cli-bad-rpc-discover",
    surface: "cli",
    name: "openclaw gateway call rpc.discover",
    category: "Invalid",
    description: "Unknown RPC method. Gateway does not expose a discovery endpoint.",
    status: "invalid",
  },

  // ============ Agent tools (built-in) ============
  {
    id: "tool-read",
    surface: "agent-tool",
    name: "Read",
    category: "Files",
    description: "Read a file. Text truncated to 2000 lines / 50KB; use offset/limit for larger files.",
    status: "built-in",
  },
  {
    id: "tool-write",
    surface: "agent-tool",
    name: "Write",
    category: "Files",
    description: "Write content to a file (creates parents, overwrites existing).",
    status: "built-in",
  },
  {
    id: "tool-edit",
    surface: "agent-tool",
    name: "Edit",
    category: "Files",
    description: "Single-file exact-text replacement. oldText must match a unique non-overlapping region.",
    status: "built-in",
  },
  {
    id: "tool-exec",
    surface: "agent-tool",
    name: "Exec",
    category: "Execution",
    description: "Run shell commands; supports backgrounding via yieldMs/background and continuation via Process.",
    status: "built-in",
  },
  {
    id: "tool-process",
    surface: "agent-tool",
    name: "Process",
    category: "Execution",
    description: "Manage running exec sessions: list, poll, log, write, send-keys, submit, paste, kill.",
    actions: ["list", "poll", "log", "write", "send-keys", "submit", "paste", "kill"],
    status: "built-in",
  },
  {
    id: "tool-cron",
    surface: "agent-tool",
    name: "Cron",
    category: "Execution",
    description: "Manage Gateway cron jobs and wake events. Use this for reminders and recurring tasks.",
    actions: ["status", "list", "add", "update", "remove", "run", "runs"],
    whenToUse: "Reminders, delayed follow-ups, recurring tasks. Don't emulate with exec sleep.",
    status: "built-in",
  },
  {
    id: "tool-yield",
    surface: "agent-tool",
    name: "Yield",
    category: "Execution",
    description: "End the current turn. Use after spawning subagents to receive their results.",
    status: "built-in",
  },
  {
    id: "tool-sessions-spawn",
    surface: "agent-tool",
    name: "Sessions (spawn)",
    category: "Sessions",
    description: "Spawn an isolated session. runtime=subagent or acp; mode=run (one-shot) or session (persistent).",
    status: "built-in",
  },
  {
    id: "tool-sessions-list",
    surface: "agent-tool",
    name: "Sessions (list)",
    category: "Sessions",
    description: "List visible sessions with filters for kind, label, agentId, search, recency.",
    status: "built-in",
  },
  {
    id: "tool-sessions-history",
    surface: "agent-tool",
    name: "Session History",
    category: "Sessions",
    description: "Fetch sanitized message history for a visible session.",
    status: "built-in",
  },
  {
    id: "tool-sessions-send",
    surface: "agent-tool",
    name: "Session Send",
    category: "Sessions",
    description: "Send a message into another visible session by sessionKey or label.",
    status: "built-in",
  },
  {
    id: "tool-sessions-status",
    surface: "agent-tool",
    name: "Session Status",
    category: "Sessions",
    description: "/status-equivalent card: usage, time, cost, linked background task context.",
    status: "built-in",
  },
  {
    id: "tool-subagents",
    surface: "agent-tool",
    name: "Subagents",
    category: "Sessions",
    description: "List, kill, or steer spawned sub-agents for this requester session.",
    status: "built-in",
  },
  {
    id: "tool-agents",
    surface: "agent-tool",
    name: "Agents",
    category: "Sessions",
    description: "List OpenClaw agent ids you can target with sessions_spawn (subagent allowlists).",
    status: "built-in",
  },
  {
    id: "tool-message",
    surface: "agent-tool",
    name: "Message",
    category: "Channels",
    description: "Send/manage messages via channel plugins (Discord, Telegram, etc).",
    actions: ["send", "broadcast", "poll", "react", "edit", "delete", "pin", "thread-create", "search"],
    status: "built-in",
  },
  {
    id: "tool-canvas",
    surface: "agent-tool",
    name: "Canvas",
    category: "Other",
    description: "Control node canvases (present/hide/navigate/eval/snapshot/A2UI).",
    status: "built-in",
  },
  {
    id: "tool-image",
    surface: "agent-tool",
    name: "Image",
    category: "Media",
    description: "Analyze one or more images with the configured image model.",
    status: "built-in",
  },
  {
    id: "tool-imagegen",
    surface: "agent-tool",
    name: "Image Generation",
    category: "Media",
    description: "Generate or edit images. Supports transparent backgrounds via outputFormat png/webp.",
    status: "built-in",
  },
  {
    id: "tool-pdf",
    surface: "agent-tool",
    name: "PDF",
    category: "Media",
    description: "Analyze PDF documents (native for Anthropic/Google, fallback for others).",
    status: "built-in",
  },
  {
    id: "tool-tts",
    surface: "agent-tool",
    name: "TTS",
    category: "Media",
    description: "Text to speech. Audio delivered automatically; reply NO_REPLY after a successful call.",
    status: "built-in",
  },
  {
    id: "tool-music",
    surface: "agent-tool",
    name: "Music Generation",
    category: "Media",
    description: "Generate music tracks; saved to OpenClaw media storage and delivered as attachments.",
    status: "built-in",
  },
  {
    id: "tool-video",
    surface: "agent-tool",
    name: "Video Generation",
    category: "Media",
    description: "Generate videos; durations may be rounded to provider-supported values.",
    status: "built-in",
  },
  {
    id: "tool-websearch",
    surface: "agent-tool",
    name: "Web Search",
    category: "Web",
    description: "DuckDuckGo search returning titles, URLs, and snippets. No API key required.",
    status: "built-in",
  },
  {
    id: "tool-webfetch",
    surface: "agent-tool",
    name: "Web Fetch",
    category: "Web",
    description: "Fetch and extract readable content from a URL (HTML → markdown/text).",
    status: "built-in",
  },
  {
    id: "tool-nodes",
    surface: "agent-tool",
    name: "Nodes",
    category: "Nodes",
    description: "Discover and control paired nodes (status/describe/pairing/notify/camera/photos/screen).",
    status: "built-in",
  },
  {
    id: "tool-gateway",
    surface: "agent-tool",
    name: "Gateway",
    category: "Other",
    description: "Restart, inspect schema paths, apply or patch config, in-place update (SIGUSR1).",
    whenToUse: "Use config.schema.lookup before edits; prefer config.patch over config.apply.",
    status: "built-in",
  },

  // ============ Connected tools ============
  {
    id: "tool-browser",
    surface: "agent-tool",
    name: "Browser",
    category: "Browser",
    description: "Browser control: status/start/stop/profiles/tabs/open/snapshot/screenshot/actions.",
    actions: ["status", "start", "snapshot", "screenshot", "actions", "open", "tabs"],
    whenToUse: "Default profile = isolated openclaw browser; use profile=user for the logged-in browser.",
    status: "connected",
  },
  {
    id: "tool-mem-get",
    surface: "agent-tool",
    name: "Memory Get",
    category: "Memory",
    description: "Safe exact excerpt read from MEMORY.md or memory/*.md with bounded line ranges.",
    status: "connected",
  },
  {
    id: "tool-mem-search",
    surface: "agent-tool",
    name: "Memory Search",
    category: "Memory",
    description: "Mandatory recall step: semantically search memory before answering history-bound questions.",
    status: "connected",
  },

  // ============ Slash commands ============
  {
    id: "slash-tools",
    surface: "slash",
    name: "/tools verbose",
    category: "Discovery",
    description: "List every tool the current agent can call, with descriptions.",
    status: "session-only",
  },
  {
    id: "slash-commands",
    surface: "slash",
    name: "/commands",
    category: "Discovery",
    description: "List slash commands available in the current session.",
    status: "session-only",
  },
  {
    id: "slash-status",
    surface: "slash",
    name: "/status",
    category: "Discovery",
    description: "Show session status: usage, model, context tokens, cost.",
    status: "session-only",
  },
  {
    id: "slash-subagents",
    surface: "slash",
    name: "/subagents list",
    category: "Discovery",
    description: "List spawned sub-agents tied to this requester session.",
    status: "session-only",
  },
];